---
apiVersion: v1
kind: Service
metadata:
  name: hackazon
spec:
  type: LoadBalancer
  selector:
    app: hackazon
  ports:
  - name: dvwa
    port: 80
    targetPort: 80
    nodePort: 30009
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: hackazon-deployment
spec:
  selector:
    matchLabels:
      app: hackazon
  replicas: 1
  template:
    metadata:
      labels:
        app: hackazon
    spec:
      containers:
      - name: hackazon
        image: harbor-01a.livefire.solutions/vulnerableapps/hackazon:latest
        ports:
        - containerPort: 80

---
apiVersion: v1
kind: Service
metadata:
  name: hackazon-svc
  labels:
    app: hackazon
spec:
  ports:
  - port: 80
    targetPort: 80
    protocol: TCP
    name: http
  selector:
    app: hackazon
  type: NodePort

---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: hackazon-ingress
  annotations:
   kubernetes.io/ingress.class: avi
spec:
  rules:
  - host: hackazon.tkg.livefire.solutions
    http:
      paths:
      - path: "/"
        pathType: Prefix
        backend:
         service:
          name: hackazon-svc
          port:
           number: 80
